# Generated by Django 3.0.9 on 2021-11-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0002_auto_20211124_1601'),
        ('shoppingmall', '0002_auto_20211124_1712'),
    ]

    operations = [
    ]
