# Generated by Django 3.0.9 on 2021-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='en_name',
            field=models.CharField(max_length=32, verbose_name='의류 속성 영어'),
        ),
    ]
